server:
  port: 8080

spring:
  application:
    name: donaton-bff


donaton.ms.logistica.url: http://localhost:8082
donaton.ms.necesidades.url: http://localhost:8083

resilience4j:
  circuitbreaker:
    instances:
      logisticaCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
      necesidades:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

# ── Logging ───────────────────────────────────────────────────────────────────
logging:
  level:
    com.donaton: DEBUG
    org.springframework.web.client: DEBUG